"""The backend protocol. Every method takes and returns plain Python values; the `Corpus`
class adds convenience (loaders, context manager) on top."""

from typing import Any, Dict, List, Optional, Sequence, Tuple, Union

Bytes = Union[bytes, str]


class Backend:
    name = "base"

    # namespace
    def ls(self, path: str) -> List[Dict[str, Any]]: ...
    def list_files(self, prefix: str) -> List[Dict[str, Any]]: ...
    def mkdir(self, path: str) -> None: ...
    def move(self, src: str, dst: str) -> None: ...
    def delete(self, path: str) -> None: ...

    # read
    def read(self, path: str) -> Tuple[bytes, int]: ...
    def read_version(self, path: str, version: int) -> bytes: ...
    def lines(self, path: str, first: int, last: int) -> bytes: ...
    def section(self, path: str, heading: str) -> Optional[bytes]: ...

    # write
    def exists(self, path: str) -> bool: ...
    def create(self, path: str, content: Bytes, author: Optional[str]) -> int: ...
    def update(self, path: str, content: Bytes, base_version: Optional[int], author: Optional[str]) -> int: ...
    def edit(self, path: str, old: Bytes, new: Bytes, author: Optional[str]) -> int: ...
    def append(self, path: str, tail: Bytes, author: Optional[str]) -> int: ...

    # history / search
    def history(self, path: str) -> List[Dict[str, Any]]: ...
    def diff(self, path: str, v1: int, v2: int) -> str: ...
    def search(self, query: str, prefix: str, limit: int) -> List[Dict[str, Any]]: ...
    def property_keys(self, prefix: str, limit: int) -> List[Dict[str, Any]]: ...
    def property_values(self, key: str, prefix: str, limit: int) -> List[Dict[str, Any]]: ...
    def property_find(self, query: str, folder: str, limit: int) -> List[Dict[str, Any]]: ...
    def outline(self, prefix: str, heading: Optional[str], mode: str, max_level: Optional[int], limit: int) -> List[Dict[str, Any]]: ...
    def heading_names(self, prefix: str, starts: str, limit: int) -> List[Dict[str, Any]]: ...
    def checkpoint(self, name: str) -> int: ...
    def export(self, prefix: str) -> List[Tuple[str, bytes]]: ...

    def close(self) -> None: ...


def to_bytes(v: Bytes) -> bytes:
    return v.encode("utf-8") if isinstance(v, str) else bytes(v)


def to_text(v: Bytes) -> str:
    return v if isinstance(v, str) else bytes(v).decode("utf-8", errors="surrogateescape")
